export const ErrorCodes = {
  INVALID_NODE_VERSION: 'INVALID_NODE_VERSION',
  BLUEPRINT_NOT_FOUND: 'BLUEPRINT_NOT_FOUND',
  INVALID_BLUEPRINT_PACKAGE_NAME: 'INVALID_BLUEPRINT_PACKAGE_NAME',
  BLUEPRINT_MANIFEST_INVALID: 'BLUEPRINT_MANIFEST_INVALID',
  BLUEPRINT_STRUCTURE_INVALID: 'BLUEPRINT_STRUCTURE_INVALID',
  BLUEPRINT_GENERATOR_NOT_FOUND: 'BLUEPRINT_GENERATOR_NOT_FOUND',
  GENERATION_CONFLICT: 'GENERATION_CONFLICT',
  GENERATION_FAILED: 'GENERATION_FAILED',
  BLUEPRINT_TEST_FAILED: 'BLUEPRINT_TEST_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const;
